name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32c3, esp32c6, esp32s3, esp32s2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1.3
          target: ${{ matrix.target }}
          path: '.'

      - name: List Build Directory
        run: |
          echo "Build directory contents:"
          ls -R build/

      - name: Prepare Release Files
        run: |
          mkdir -p release-files
          cp build/bme680-wifi-sensor-firmware.bin release-files/bme680-${{ matrix.target }}.bin
          cp build/bootloader/bootloader.bin release-files/bootloader-${{ matrix.target }}.bin
          cp build/partition_table/partition-table.bin release-files/partition-table-${{ matrix.target }}.bin
          echo "Release files prepared:"
          ls -l release-files/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          files: |
            release-files/bme680-${{ matrix.target }}.bin
            release-files/bootloader-${{ matrix.target }}.bin
            release-files/partition-table-${{ matrix.target }}.bin
